/**
 * MediaSource playback — the pump
 * (docs/playback.md, "The renderer: MediaSource, not `src`").
 *
 * ## Why this module exists
 *
 * A plain `<video src>` hands buffering policy to Chromium's progressive loader.
 * Against a static file that is fine. Against one of our open-ended ffmpeg pipes
 * — no `Content-Length`, `Accept-Ranges: none` — it is the entire bug: when its
 * buffer fills, the loader stops reading, the socket sits zero-window, and
 * Chromium eventually *drops the connection itself* and silently re-requests the
 * same URL. A re-fetch of a file costs milliseconds; a re-fetch of a live
 * transcode restarts ffmpeg at 0:00, so playback freezes until the fresh encode
 * catches back up to the playhead. Deep into an episode that measured 159
 * seconds of dead air.
 *
 * So the renderer fetches the pipe itself and feeds a `MediaSource`. We choose
 * when to read, which means the connection is never abandoned; and we get a real
 * duration, honest `buffered` ranges, and a true end-of-stream for free.
 *
 * ## Why it is DOM-free
 *
 * Everything here talks to structural interfaces (`MediaSourceLike`,
 * `SourceBufferLike`, `ByteReader`) that the real DOM types satisfy. That is not
 * ceremony: it is what lets the box scanner, the codec-string derivation and the
 * whole read/append/evict state machine be unit-tested in `tests/mse.test.ts`
 * against real ffmpeg-generated bytes and a scripted fake reader, in Node, with
 * no browser. The DOM-touching glue — `new MediaSource()`, `fetch`, object URLs —
 * lives in `Player.tsx`, and is the only part that isn't covered.
 *
 * ## The read policy
 *
 * Read until 60s are buffered ahead of the playhead, then stop reading. TCP
 * backpressure throttles ffmpeg exactly as it did before — the difference is
 * that *we* are the ones not reading, so nobody drops the connection. Resume
 * below 15s. Evict anything more than 120s behind the playhead so renderer
 * memory stays flat across a 3-hour session, and on `QuotaExceededError` evict
 * harder and retry rather than failing the stream.
 */

// ---------------------------------------------------------------------------
// Buffer policy
// ---------------------------------------------------------------------------

export interface BufferPolicy {
    /** Stop reading once this many seconds are buffered ahead of the playhead. */
    highWaterS: number;
    /** Start reading again at or below this. Hysteresis, so the reader isn't flapping. */
    lowWaterS: number;
    /** Seconds of already-played media kept behind the playhead. */
    backBufferS: number;
    /** What a `QuotaExceededError` evicts back to before retrying the append. */
    tightBackBufferS: number;
    /** How often a paused reader re-checks whether there is room. */
    pollMs: number;
}

export const DEFAULT_BUFFER_POLICY: BufferPolicy = {
    highWaterS: 60,
    lowWaterS: 15,
    backBufferS: 120,
    tightBackBufferS: 10,
    pollMs: 250,
};

/**
 * A standby pump (phase 3): buffer the first few seconds of the next episode so
 * the handoff is instant, then stop — a hidden element must not sit on 60s of
 * decoded video, and its ffmpeg must not race the one that is actually on air.
 */
export const STANDBY_BUFFER_POLICY: BufferPolicy = {
    ...DEFAULT_BUFFER_POLICY,
    highWaterS: 15,
    lowWaterS: 12,
};

// ---------------------------------------------------------------------------
// Box reading
// ---------------------------------------------------------------------------

/** The stream is not the fragmented MP4 we can feed to a `SourceBuffer`. */
export class Mp4ParseError extends Error {
    constructor(message: string) {
        super(message);
        this.name = "Mp4ParseError";
    }
}

const BOX_HEADER_BYTES = 8;

/**
 * Top-level boxes that are legal in the byte stream but carry nothing a
 * `SourceBuffer` needs. `mfra` is the one that actually turns up: ffmpeg writes
 * a fragment random-access index when it closes the file, i.e. right at the end
 * of every episode.
 */
const IGNORED_BOXES = new Set([
    "free",
    "skip",
    "wide",
    "styp",
    "sidx",
    "ssix",
    "mfra",
    "uuid",
]);

function readU16(bytes: Uint8Array, at: number): number {
    return (bytes[at] << 8) | bytes[at + 1];
}

function readU32(bytes: Uint8Array, at: number): number {
    return (
        ((bytes[at] << 24) |
            (bytes[at + 1] << 16) |
            (bytes[at + 2] << 8) |
            bytes[at + 3]) >>>
        0
    );
}

function readFourCc(bytes: Uint8Array, at: number): string {
    return String.fromCharCode(
        bytes[at],
        bytes[at + 1],
        bytes[at + 2],
        bytes[at + 3],
    );
}

interface BoxHeader {
    type: string;
    /** Total box size including the header. */
    size: number;
    /** 8 normally, 16 for the 64-bit `largesize` form. */
    headerSize: number;
}

/**
 * Null means "not enough bytes yet, ask again". A box declaring size 0 ("runs to
 * the end of the file") throws instead: in a live stream we would never learn
 * where it ended, and ffmpeg's fragmented muxer never emits one.
 */
function readBoxHeader(bytes: Uint8Array, at: number): BoxHeader | null {
    if (bytes.length - at < BOX_HEADER_BYTES) return null;
    const declared = readU32(bytes, at);
    const type = readFourCc(bytes, at + 4);

    if (declared === 1) {
        if (bytes.length - at < 16) return null;
        // JS numbers hold this exactly up to 2^53; a media box never approaches it.
        const size = readU32(bytes, at + 8) * 2 ** 32 + readU32(bytes, at + 12);
        if (size < 16)
            throw new Mp4ParseError(
                `box ${type} declares an impossible size ${size}`,
            );
        return { type, size, headerSize: 16 };
    }
    if (declared === 0) {
        throw new Mp4ParseError(
            `box ${type} runs to end-of-file, which a live stream cannot deliver`,
        );
    }
    if (declared < BOX_HEADER_BYTES) {
        throw new Mp4ParseError(
            `box ${type} declares an impossible size ${declared}`,
        );
    }
    return { type, size: declared, headerSize: BOX_HEADER_BYTES };
}

function concat(parts: Uint8Array[]): Uint8Array {
    if (parts.length === 1) return parts[0];
    const total = parts.reduce((sum, part) => sum + part.length, 0);
    const out = new Uint8Array(total);
    let at = 0;
    for (const part of parts) {
        out.set(part, at);
        at += part.length;
    }
    return out;
}

/** One box: `body` is the whole box, `payload` is everything after the header. */
interface Box {
    type: string;
    body: Uint8Array;
    payload: Uint8Array;
}

/** Iterate the boxes laid out back to back in `bytes`. Trailing junk is ignored. */
function* boxes(bytes: Uint8Array): Generator<Box> {
    let at = 0;
    for (;;) {
        let header: BoxHeader | null;
        try {
            header = readBoxHeader(bytes, at);
        } catch {
            return;
        }
        if (!header || bytes.length - at < header.size) return;
        yield {
            type: header.type,
            body: bytes.subarray(at, at + header.size),
            payload: bytes.subarray(at + header.headerSize, at + header.size),
        };
        at += header.size;
    }
}

function findBox(bytes: Uint8Array, type: string): Box | null {
    for (const box of boxes(bytes)) if (box.type === type) return box;
    return null;
}

/** `moov → trak → mdia → minf` style descent, returning the last box's payload. */
function descend(bytes: Uint8Array, path: string[]): Uint8Array | null {
    let current = bytes;
    for (const type of path) {
        const box = findBox(current, type);
        if (!box) return null;
        current = box.payload;
    }
    return current;
}

// ---------------------------------------------------------------------------
// The segment scanner
// ---------------------------------------------------------------------------

/**
 * MSE wants the byte stream cut into an **initialisation segment** (`ftyp` +
 * `moov`) followed by **media segments** (`moof` + `mdat` pairs). ffmpeg's
 * `frag_keyframe+empty_moov+default_base_moof` output is exactly that shape, but
 * it arrives in arbitrary TCP-sized chunks, so this reassembles it.
 */
export type Mp4Segment =
    | { kind: "init"; data: Uint8Array }
    | { kind: "media"; data: Uint8Array };

export class Mp4SegmentScanner {
    /** Bytes seen but not yet forming a complete box. */
    private pending: Uint8Array = new Uint8Array(0);
    private initParts: Uint8Array[] = [];
    private sawMoov = false;
    /** A `moof` waiting for its `mdat` — the two are appended as one segment. */
    private pendingMoof: Uint8Array | null = null;

    push(chunk: Uint8Array): void {
        this.pending =
            this.pending.length === 0 ? chunk : concat([this.pending, chunk]);
    }

    /**
     * Every segment that has become complete since the last call. Throws
     * `Mp4ParseError` on a stream that isn't the shape we asked ffmpeg for — the
     * caller's cue to fall back to a plain `<video src>` for this episode.
     */
    drain(): Mp4Segment[] {
        const out: Mp4Segment[] = [];
        let at = 0;

        for (;;) {
            const header = readBoxHeader(this.pending, at);
            if (!header || this.pending.length - at < header.size) break;
            const body = this.pending.subarray(at, at + header.size);
            at += header.size;
            this.consume(header.type, body, out);
        }

        // Keep only the incomplete tail. `slice` (a copy) rather than `subarray` so
        // the consumed prefix — up to a whole fragment — becomes collectable.
        if (at > 0) this.pending = this.pending.slice(at);
        return out;
    }

    /** True once the init segment has been emitted. */
    get initialised(): boolean {
        return this.sawMoov;
    }

    private consume(type: string, body: Uint8Array, out: Mp4Segment[]): void {
        if (!this.sawMoov) {
            if (type === "ftyp" || type === "moov") {
                this.initParts.push(body);
                if (type === "moov") {
                    this.sawMoov = true;
                    out.push({ kind: "init", data: concat(this.initParts) });
                    this.initParts = [];
                }
                return;
            }
            if (IGNORED_BOXES.has(type)) return;
            throw new Mp4ParseError(`saw ${type} before the moov box`);
        }

        if (type === "moof") {
            // Two moofs in a row means we lost an mdat, and appending a fragment
            // header with no samples would corrupt the buffer silently.
            if (this.pendingMoof)
                throw new Mp4ParseError("moof with no mdat after it");
            this.pendingMoof = body;
            return;
        }
        if (type === "mdat") {
            if (!this.pendingMoof)
                throw new Mp4ParseError("mdat with no moof before it");
            out.push({ kind: "media", data: concat([this.pendingMoof, body]) });
            this.pendingMoof = null;
            return;
        }
        if (IGNORED_BOXES.has(type)) return;
        throw new Mp4ParseError(`unexpected top-level box ${type}`);
    }
}

// ---------------------------------------------------------------------------
// Codec strings
// ---------------------------------------------------------------------------

/**
 * `addSourceBuffer` needs a full MIME type with RFC 6381 codec parameters —
 * `video/mp4; codecs="avc1.640028,mp4a.40.2"`. Chromium will not guess, so the
 * strings have to be derived from the init segment's sample descriptions.
 */
export interface InitSegmentInfo {
    /** e.g. `avc1.640028`. */
    video: string | null;
    /** e.g. `mp4a.40.2`; null for a genuinely silent file. */
    audio: string | null;
    /** What to hand `addSourceBuffer`. */
    mime: string;
}

/** Fixed-field prefix of a `VisualSampleEntry` payload, before its child boxes. */
const VISUAL_ENTRY_PREFIX = 78;
/** Fixed-field prefix of a version-0 `AudioSampleEntry` payload. */
const AUDIO_ENTRY_PREFIX = 28;

const AVC_ENTRY_TYPES = new Set(["avc1", "avc2", "avc3", "avc4"]);

function hex2(byte: number): string {
    return byte.toString(16).padStart(2, "0").toUpperCase();
}

/**
 * `avcC` opens with configurationVersion, then the three bytes RFC 6381 wants
 * verbatim: profile, profile-compatibility, level. `avc1.640028` is High profile
 * at level 4.0 — what our own transcode path produces.
 *
 * The sample entry's own fourcc leads, because `avc1` and `avc3` differ in where
 * parameter sets live and Chromium cares about the distinction.
 */
function avcCodecString(
    entryType: string,
    entryPayload: Uint8Array,
): string | null {
    const avcC = findBox(entryPayload.subarray(VISUAL_ENTRY_PREFIX), "avcC");
    if (!avcC || avcC.payload.length < 4) return null;
    const [, profile, compatibility, level] = avcC.payload;
    return `${entryType}.${hex2(profile)}${hex2(compatibility)}${hex2(level)}`;
}

interface Descriptor {
    tag: number;
    length: number;
    /** Offset of the descriptor's own payload. */
    start: number;
}

/**
 * MPEG-4 descriptors: a tag byte, then a base-128 length of up to four bytes,
 * then the payload. Used only inside `esds`.
 */
function readDescriptor(bytes: Uint8Array, at: number): Descriptor | null {
    if (at < 0 || at >= bytes.length) return null;
    const tag = bytes[at];
    let cursor = at + 1;
    let length = 0;
    for (let byteIndex = 0; byteIndex < 4; byteIndex++) {
        if (cursor >= bytes.length) return null;
        const byte = bytes[cursor++];
        length = (length << 7) | (byte & 0x7f);
        if ((byte & 0x80) === 0) break;
    }
    return { tag, length, start: cursor };
}

const TAG_ES = 0x03;
const TAG_DECODER_CONFIG = 0x04;
const TAG_DECODER_SPECIFIC = 0x05;
/** objectTypeIndication for MPEG-4 audio — i.e. "read the AudioSpecificConfig". */
const OTI_MPEG4_AUDIO = 0x40;
/** MPEG-2 and MPEG-1 Part 3 audio: both are mp3 as far as a codec string goes. */
const OTI_MP3 = new Set([0x69, 0x6b]);
/** Fixed fields of a DecoderConfigDescriptor before its DecoderSpecificInfo. */
const DECODER_CONFIG_PREFIX = 13;

/**
 * Walk `esds` far enough to name the codec: ES descriptor → decoder config →
 * object type, and for MPEG-4 audio one more hop into the AudioSpecificConfig
 * for the audio object type (2 = AAC-LC, which is what everything we produce
 * is, but 5/29 for HE-AAC do turn up in remuxed sources).
 */
function esdsCodecString(esdsPayload: Uint8Array): string | null {
    // esds is a FullBox: skip version + flags.
    const es = readDescriptor(esdsPayload, 4);
    if (!es || es.tag !== TAG_ES) return null;

    let cursor = es.start + 2; // ES_ID
    if (cursor >= esdsPayload.length) return null;
    const flags = esdsPayload[cursor];
    cursor += 1;
    if (flags & 0x80) cursor += 2; // dependsOn_ES_ID
    if (flags & 0x40) cursor += 1 + (esdsPayload[cursor] ?? 0); // URL
    if (flags & 0x20) cursor += 2; // OCR_ES_Id

    const config = readDescriptor(esdsPayload, cursor);
    if (!config || config.tag !== TAG_DECODER_CONFIG) return null;
    if (config.start >= esdsPayload.length) return null;

    const objectType = esdsPayload[config.start];
    if (OTI_MP3.has(objectType)) return "mp4a.6b";
    if (objectType !== OTI_MPEG4_AUDIO) return null;

    let audioObjectType = 2;
    const specific = readDescriptor(
        esdsPayload,
        config.start + DECODER_CONFIG_PREFIX,
    );
    if (
        specific &&
        specific.tag === TAG_DECODER_SPECIFIC &&
        specific.start < esdsPayload.length
    ) {
        const first = esdsPayload[specific.start];
        audioObjectType = first >> 3;
        // 31 is the escape value: the real type is the next six bits, plus 32.
        if (audioObjectType === 31 && specific.start + 1 < esdsPayload.length) {
            audioObjectType =
                32 +
                (((first & 0x07) << 3) |
                    (esdsPayload[specific.start + 1] >> 5));
        }
    }
    return `mp4a.40.${audioObjectType}`;
}

/**
 * The four soundtracks that can reach a `SourceBuffer` from our pipes: AAC (both
 * from the transcode path and from remuxed AAC sources), mp3, Opus and FLAC.
 * Anything else returns null and the episode falls back to plain `src`.
 */
function audioCodecString(
    entryType: string,
    entryPayload: Uint8Array,
): string | null {
    const children = entryPayload.subarray(AUDIO_ENTRY_PREFIX);
    switch (entryType) {
        case "mp4a": {
            const esds = findBox(children, "esds");
            // A missing or unreadable esds is not fatal: `mp4a` in a fragmented MP4 is
            // AAC-LC in every stream we produce, and a wrong guess here would only
            // cost the fallback we were already going to take.
            return (esds && esdsCodecString(esds.payload)) ?? "mp4a.40.2";
        }
        case ".mp3":
        case "mp3 ":
            return "mp4a.6b";
        case "Opus":
        case "opus":
            return "opus";
        case "fLaC":
        case "flac":
            return "flac";
        default:
            return null;
    }
}

/** `mdia/hdlr` names the track kind: `vide`, `soun`, `sbtl`, … */
function handlerType(trakPayload: Uint8Array): string | null {
    const hdlr = descend(trakPayload, ["mdia", "hdlr"]);
    // FullBox version+flags (4) then pre_defined (4), then the handler fourcc.
    if (!hdlr || hdlr.length < 12) return null;
    return readFourCc(hdlr, 8);
}

/** The sample entries inside an `stsd` payload. */
function* sampleEntries(stsdPayload: Uint8Array): Generator<Box> {
    // FullBox version+flags (4) then entry_count (4).
    if (stsdPayload.length < 8) return;
    yield* boxes(stsdPayload.subarray(8));
}

/**
 * Derive the `addSourceBuffer` type from an init segment, or null when the
 * stream is one this parser cannot describe — an exotic remuxed codec, say. Null
 * is a normal outcome, not an error: the caller falls back to a plain
 * `<video src>` for that episode and is then no worse off than before phase 2.
 *
 * A video track is required (these are television episodes); audio is optional,
 * because a silent file is a real thing the remux path serves.
 */
export function parseInitSegment(init: Uint8Array): InitSegmentInfo | null {
    const moov = findBox(init, "moov");
    if (!moov) return null;

    let video: string | null = null;
    let audio: string | null = null;

    for (const box of boxes(moov.payload)) {
        if (box.type !== "trak") continue;
        const kind = handlerType(box.payload);
        if (kind !== "vide" && kind !== "soun") continue;

        const stsd = descend(box.payload, ["mdia", "minf", "stbl", "stsd"]);
        if (!stsd) return null;

        let described = false;
        for (const entry of sampleEntries(stsd)) {
            if (kind === "vide") {
                if (!AVC_ENTRY_TYPES.has(entry.type)) continue;
                const codec = avcCodecString(entry.type, entry.payload);
                if (codec === null) continue;
                video ??= codec;
            } else {
                const codec = audioCodecString(entry.type, entry.payload);
                if (codec === null) continue;
                audio ??= codec;
            }
            described = true;
            break;
        }
        // A track we can see but cannot name would be dropped silently by the
        // browser, so refuse the whole stream and let the fallback handle it.
        if (!described) return null;
    }

    if (video === null) return null;
    const codecs = audio === null ? video : `${video},${audio}`;
    return { video, audio, mime: `video/mp4; codecs="${codecs}"` };
}

/**
 * Video resolution out of the first `avc1`-family sample entry. Not needed for
 * playback — it is here because `tests/mse.test.ts` uses it to prove the box
 * walk is landing on the real sample description rather than on a lucky offset.
 */
export function parseVideoSize(
    init: Uint8Array,
): { width: number; height: number } | null {
    const moov = findBox(init, "moov");
    if (!moov) return null;
    for (const box of boxes(moov.payload)) {
        if (box.type !== "trak" || handlerType(box.payload) !== "vide")
            continue;
        const stsd = descend(box.payload, ["mdia", "minf", "stbl", "stsd"]);
        if (!stsd) return null;
        for (const entry of sampleEntries(stsd)) {
            if (!AVC_ENTRY_TYPES.has(entry.type)) continue;
            // width/height sit 24 bytes into the VisualSampleEntry payload.
            return {
                width: readU16(entry.payload, 24),
                height: readU16(entry.payload, 26),
            };
        }
    }
    return null;
}

// ---------------------------------------------------------------------------
// The pump
// ---------------------------------------------------------------------------

export interface TimeRangesLike {
    readonly length: number;
    start(index: number): number;
    end(index: number): number;
}

/**
 * What `appendBuffer` accepts. Spelled wider than `Uint8Array` deliberately: the
 * DOM's `BufferSource` is pinned to a non-shared `ArrayBuffer`, and this module
 * has to typecheck against both the DOM lib (where the real `SourceBuffer` lives)
 * and the Node lib (where its tests run).
 */
export type AppendData = ArrayBufferView | ArrayBufferLike;

export interface SourceBufferLike {
    readonly updating: boolean;
    readonly buffered: TimeRangesLike;
    appendBuffer(data: AppendData): void;
    remove(start: number, end: number): void;
    addEventListener(type: string, listener: () => void): void;
    removeEventListener(type: string, listener: () => void): void;
}

export interface MediaSourceLike {
    readonly readyState: string;
    duration: number;
    addSourceBuffer(type: string): SourceBufferLike;
    endOfStream(): void;
}

/** Where the playhead is. `HTMLMediaElement` satisfies this. */
export interface MediaClock {
    readonly currentTime: number;
}

/** A `ReadableStreamDefaultReader<Uint8Array>`, structurally. */
export interface ByteReader {
    read(): Promise<{ done: boolean; value?: Uint8Array }>;
    cancel(reason?: unknown): unknown;
}

/** An `AbortSignal`, structurally — the pump only ever reads `aborted`. */
export interface AbortLike {
    readonly aborted: boolean;
}

export interface PumpOptions {
    /**
     * Opens the byte stream. A function rather than a reader so the pump owns the
     * whole lifecycle including the failure of the request itself.
     */
    openReader(): Promise<ByteReader>;
    mediaSource: MediaSourceLike;
    clock: MediaClock;
    /**
     * Episode runtime *minus the seek offset*, so the scrub bar stops guessing.
     * The pipe's own timestamps restart at zero after an `-ss` seek, which is the
     * same reason the Player keeps a display offset.
     */
    durationS?: number | null;
    signal?: AbortLike;
    policy?: Partial<BufferPolicy>;
    /** Read targets `promote()` switches to. Defaults to the full policy. */
    promotedPolicy?: Partial<BufferPolicy>;
    /**
     * The stream defeated the parser. The caller should re-render this episode
     * with a plain `<video src>`; behaviour is then exactly what it was before
     * phase 2, which is worse but not broken.
     */
    onFallback?(reason: string): void;
    /** A real failure: the request died, or the SourceBuffer rejected the data. */
    onError?(error: Error): void;
    /** Test seam. The pump's only wait primitive. */
    sleep?(ms: number): Promise<void>;
}

export interface PumpStats {
    /** False while the reader is parked because the buffer is full. */
    reading: boolean;
    bytes: number;
    /** Media segments appended, not counting the init segment. */
    segments: number;
    /** Back-buffer evictions performed. */
    trims: number;
    /** Appends that hit `QuotaExceededError` and had to evict and retry. */
    quotaRetries: number;
    /** Set once the source has been told the stream is complete. */
    endedStream: boolean;
    fellBack: boolean;
    mime: string | null;
}

export interface Pump {
    readonly stats: PumpStats;
    /** Resolves when the pump stops for any reason: EOF, abort, fallback, error. */
    readonly done: Promise<void>;
    /**
     * Switch to the full read targets. Phase 3's standby pump buffers ~15s while
     * it is hidden and calls this the moment it becomes the picture on screen.
     */
    promote(): void;
    stop(): void;
}

function defaultSleep(ms: number): Promise<void> {
    return new Promise((resolve) => setTimeout(resolve, ms));
}

/** DOMException surfaces this by name; the numeric code is the older spelling. */
function isQuotaExceeded(err: unknown): boolean {
    if (typeof err !== "object" || err === null) return false;
    const candidate = err as { name?: unknown; code?: unknown };
    return candidate.name === "QuotaExceededError" || candidate.code === 22;
}

function isAbort(err: unknown): boolean {
    return (
        typeof err === "object" &&
        err !== null &&
        (err as { name?: unknown }).name === "AbortError"
    );
}

function asError(err: unknown): Error {
    return err instanceof Error ? err : new Error(String(err));
}

/**
 * Start pumping `openReader()`'s bytes into `mediaSource`.
 *
 * The loop is deliberately sequential — read, scan, append, check for room, read
 * again — because every interesting property falls out of that ordering: appends
 * are serialised without an explicit queue (each one is awaited), the reader
 * cannot outrun the buffer, and "stop reading" is simply "don't call `read()`",
 * which is what keeps the connection alive instead of letting Chromium abandon it.
 */
export function startPump(options: PumpOptions): Pump {
    const policy: BufferPolicy = {
        ...DEFAULT_BUFFER_POLICY,
        ...options.policy,
    };
    const promoted: BufferPolicy = {
        ...DEFAULT_BUFFER_POLICY,
        ...options.promotedPolicy,
    };
    const sleep = options.sleep ?? defaultSleep;
    const scanner = new Mp4SegmentScanner();

    const stats: PumpStats = {
        reading: true,
        bytes: 0,
        segments: 0,
        trims: 0,
        quotaRetries: 0,
        endedStream: false,
        fellBack: false,
        mime: null,
    };

    let stopped = false;
    let reader: ByteReader | null = null;
    let sourceBuffer: SourceBufferLike | null = null;

    const aborted = (): boolean => stopped || options.signal?.aborted === true;
    const isOpen = (): boolean => options.mediaSource.readyState === "open";

    // ---- source buffer operations -------------------------------------------

    /**
     * `appendBuffer` and `remove` are both asynchronous and both refuse to start
     * while `updating` — so every operation is awaited to completion. Because the
     * pump is the only thing touching this SourceBuffer, awaiting is the whole
     * queue.
     */
    function operate(run: (sb: SourceBufferLike) => void): Promise<void> {
        const sb = sourceBuffer;
        if (!sb) return Promise.reject(new Error("no source buffer yet"));
        return new Promise<void>((resolve, reject) => {
            const cleanup = (): void => {
                sb.removeEventListener("updateend", onDone);
                sb.removeEventListener("error", onError);
            };
            const onDone = (): void => {
                cleanup();
                resolve();
            };
            const onError = (): void => {
                cleanup();
                // Chromium's MSE demuxer is stricter than its progressive one — it will
                // refuse an init segment the plain-`src` path plays without complaint.
                // So a rejection here is a *parse* failure, which means fall back to
                // plain playback for this episode rather than show a failure card.
                reject(
                    new Mp4ParseError("the source buffer rejected the data"),
                );
            };
            sb.addEventListener("updateend", onDone);
            sb.addEventListener("error", onError);
            try {
                run(sb);
            } catch (err) {
                cleanup();
                reject(err);
            }
        });
    }

    async function waitIdle(): Promise<void> {
        while (sourceBuffer?.updating === true && !aborted())
            await sleep(policy.pollMs);
    }

    /**
     * Evict everything more than `keepS` behind the playhead.
     *
     * Reads `buffered.start(0)` alone because on this path the buffer is always
     * one contiguous range: a seek is a *URL reload* (see `Player.tsx`), never a
     * jump within the stream, so nothing ever appends across a gap. If that ever
     * changes, this has to walk every range instead.
     */
    async function trim(keepS: number): Promise<void> {
        const sb = sourceBuffer;
        if (!sb || sb.buffered.length === 0) return;
        const start = sb.buffered.start(0);
        const cutoff = Math.max(0, options.clock.currentTime - keepS);
        // A hair of slack: removing a sliver every poll would be pure churn.
        if (cutoff - start < 1) return;
        await waitIdle();
        if (aborted()) return;
        await operate((buffer) => buffer.remove(start, cutoff));
        stats.trims += 1;
    }

    /**
     * `QuotaExceededError` is the spec's "buffer is full" and the documented
     * remedy is to evict and retry rather than to fail — a 3-hour session must not
     * end in a broken stream because the back buffer got fat.
     */
    async function append(data: Uint8Array): Promise<void> {
        try {
            await operate((buffer) => buffer.appendBuffer(data));
            return;
        } catch (err) {
            if (!isQuotaExceeded(err)) throw err;
        }
        stats.quotaRetries += 1;
        await trim(policy.tightBackBufferS);
        try {
            await operate((buffer) => buffer.appendBuffer(data));
            return;
        } catch (err) {
            if (!isQuotaExceeded(err)) throw err;
        }
        // Last resort: everything behind the playhead goes.
        await trim(0);
        await operate((buffer) => buffer.appendBuffer(data));
    }

    // ---- read pacing --------------------------------------------------------

    /** Seconds of media buffered ahead of the playhead. */
    function bufferedAhead(): number {
        const sb = sourceBuffer;
        if (!sb) return 0;
        const ranges = sb.buffered;
        const now = options.clock.currentTime;
        for (let i = 0; i < ranges.length; i++) {
            // A shade of tolerance at the start: a fresh stream's first fragment can
            // begin a few milliseconds after zero.
            if (now >= ranges.start(i) - 0.5 && now <= ranges.end(i))
                return ranges.end(i) - now;
        }
        if (ranges.length === 0) return 0;
        // The playhead is outside every range (a seek, or a gap). Measure from the
        // last range so a paused element still stops the reader somewhere sane.
        return Math.max(0, ranges.end(ranges.length - 1) - now);
    }

    /**
     * Park the reader while the buffer is full. Returns once there is room, or
     * once the pump has been stopped.
     *
     * This is the fix, in five lines: not reading is what applies TCP backpressure
     * to ffmpeg — the same throttle the old `<video src>` path relied on — without
     * anybody dropping the connection to achieve it.
     */
    async function waitForRoom(): Promise<void> {
        if (!sourceBuffer) return;
        while (!aborted()) {
            await trim(policy.backBufferS);
            const ahead = bufferedAhead();
            if (stats.reading) {
                if (ahead < policy.highWaterS) return;
                stats.reading = false;
            } else if (ahead <= policy.lowWaterS) {
                stats.reading = true;
                return;
            }
            await sleep(policy.pollMs);
        }
    }

    // ---- segment handling ---------------------------------------------------

    function setDuration(): void {
        const duration = options.durationS;
        if (duration == null || !(duration > 0) || !isOpen()) return;
        try {
            options.mediaSource.duration = duration;
        } catch {
            // Only ever a transient InvalidStateError; the scrub bar falling back to
            // the element's own guess is not worth failing playback over.
        }
    }

    async function consume(segment: Mp4Segment): Promise<void> {
        if (segment.kind === "init") {
            const info = parseInitSegment(segment.data);
            if (!info) {
                throw new Mp4ParseError(
                    "no usable codec string in the initialisation segment",
                );
            }
            stats.mime = info.mime;
            try {
                sourceBuffer = options.mediaSource.addSourceBuffer(info.mime);
            } catch (err) {
                // A codec string we derived correctly but this build cannot decode. Same
                // remedy as a stream we couldn't parse at all: hand the episode back to
                // the plain-`src` path, which at least knows how to ask Chromium.
                throw new Mp4ParseError(
                    `the browser refused codecs ${info.mime}: ${asError(err).message}`,
                );
            }
            await append(segment.data);
            setDuration();
            return;
        }
        if (!sourceBuffer)
            throw new Mp4ParseError(
                "a media fragment arrived before the moov box",
            );
        await append(segment.data);
        stats.segments += 1;
    }

    /** ffmpeg closed the pipe: the episode is complete, so say so. */
    async function finish(): Promise<void> {
        await waitIdle();
        if (aborted() || !isOpen()) return;
        try {
            options.mediaSource.endOfStream();
            stats.endedStream = true;
        } catch {
            // A source already closed by teardown; the element has nothing left to do.
        }
    }

    function fallback(reason: string): void {
        if (stats.fellBack) return;
        stats.fellBack = true;
        options.onFallback?.(reason);
    }

    // ---- the loop -----------------------------------------------------------

    async function run(): Promise<void> {
        try {
            reader = await options.openReader();
        } catch (err) {
            if (!aborted() && !isAbort(err)) options.onError?.(asError(err));
            return;
        }

        try {
            for (;;) {
                await waitForRoom();
                if (aborted()) return;

                const chunk = await reader.read();
                // Abort before EOF: cancelling a reader makes the pending read report
                // `done`, and a torn-down stream must never be called complete.
                if (aborted()) return;
                if (chunk.done) {
                    await finish();
                    return;
                }
                if (!chunk.value || chunk.value.length === 0) continue;

                stats.bytes += chunk.value.length;
                scanner.push(chunk.value);
                for (const segment of scanner.drain()) {
                    await consume(segment);
                    if (aborted()) return;
                }
            }
        } catch (err) {
            if (aborted() || isAbort(err)) return;
            if (err instanceof Mp4ParseError) fallback(err.message);
            else options.onError?.(asError(err));
        } finally {
            // Cancelling closes the socket, which is what tells the stream server to
            // kill this episode's ffmpeg. Never leave that to a garbage collector.
            try {
                await reader?.cancel();
            } catch {
                /* A reader that is already closed or errored has nothing to cancel. */
            }
        }
    }

    const done = run();

    return {
        stats,
        done,
        promote(): void {
            // Every field, not the three that happened to differ: leaving
            // `tightBackBufferS`/`pollMs` behind meant a promoted policy could
            // silently only half-apply, which is invisible until someone sets
            // them to something other than the standby's values.
            Object.assign(policy, promoted);
        },
        stop(): void {
            stopped = true;
            // Don't wait for the read loop to notice: dropping the reader now is what
            // frees the encoder.
            void Promise.resolve(reader?.cancel()).catch(() => undefined);
        },
    };
}
